### ISSUE TITLE
Case where regularization parameter == 0

### ISSUE THREAD

**Issue by JSchuurmans** [TUDelft-DeTAIL/tensorized_kernel_methods#3]
There is a more efficient way of solving the linear system when `l=0`.

**Comment by fwesel** [comment]
Both in that case and with regularization, there is NO more efficient method from a computational and memory point of view than solving:

$C^T C + \lambda R = C^T y$.

However, the linear system can be solved (both with regularization, and without) using the following:

$[C; \sqrt{R} I]^T [C; \sqrt{R} I = [y; 0]$,

which can be solved say using Matlab with $[C; \sqrt{R} I]\backslash[y; 0]$.

This formulation enables more  accurate solution as the system is better conditioned. In the case of $\lambda=0$, you can simply solve then with $C\y$.

Now one problem is that if you were to implement this solve method in the general case, you need access to the matrix square root (Cholesky decomposition) of $R$. This may be hard to compute if the $R$ is badly conditioned. I will look into how to do this, as this solution method might be preferable for smaller problems. Note that in this case, you do need $C$ in storage, which can become **very** large in size for big data. This is not the case in the current implementation, where you compute $C^C$ in batches, thereby avoiding the storage of $C$.

**Comment by fwesel** [comment]
I will look into how to perform this Cholesky factorization of $R$, and see if it is possible to avoid it. This solution method is more accurate, more slow, and more memory inefficient.
